# Generated by Django 5.0.1 on 2024-02-08 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='linker',
            name='combined_url',
            field=models.CharField(default='http://127.0.0.1:8000/', max_length=256),
        ),
    ]
