# Generated by Django 5.0.1 on 2024-02-28 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_linker_combined_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='linker',
            name='expiration_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='expiration date'),
        ),
        migrations.AlterField(
            model_name='linker',
            name='combined_url',
            field=models.CharField(max_length=256),
        ),
    ]
